### ISSUE TITLE
getting error

### ISSUE THREAD

**Issue by omergunal** [python-security/pyt#175]
```
python3 -m pyt x.py

Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/gunal/pyt/pyt/__main__.py", line 10, in <module>
    from .cfg import make_cfg
  File "/home/gunal/pyt/pyt/cfg/__init__.py", line 1, in <module>
    from .make_cfg import make_cfg
  File "/home/gunal/pyt/pyt/cfg/make_cfg.py", line 1, in <module>
    from .expr_visitor import ExprVisitor
  File "/home/gunal/pyt/pyt/cfg/expr_visitor.py", line 31, in <module>
    from .stmt_visitor import StmtVisitor
  File "/home/gunal/pyt/pyt/cfg/stmt_visitor.py", line 58, in <module>
    uninspectable_modules = {module.name for module in iter_modules()}  # Don't warn about failing to import these
  File "/home/gunal/pyt/pyt/cfg/stmt_visitor.py", line 58, in <setcomp>
    uninspectable_modules = {module.name for module in iter_modules()}  # Don't warn about failing to import these
AttributeError: 'tuple' object has no attribute 'name'
```

**Comment by KevinHock** [comment]
What is `x.py`?

**Comment by omergunal** [comment]
I tried to scan x.py file

**Comment by KevinHock** [comment]
Run `cat x.py`

**Comment by bcaller** [comment]
You are running pyt with python 3.5.

Try running it in a python 3.6 environment.

**Comment by omergunal** [comment]
@KevinHock 
```
cat x.py 
x = (1,2,3)

a = {i for i in x}

print(a)
```

@bcaller  yes, it worked with python3.6
